import json, base64
from io import BytesIO
from pathlib import Path
from PIL import Image as PILImage
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from reportlab.platypus import BaseDocTemplate, PageTemplate, Frame, Paragraph, Spacer, PageBreak, Table, TableStyle, Image
from reportlab.lib.units import mm

NAVY=colors.HexColor('#0B1D32'); TEXT=colors.HexColor('#1A2433'); PALE=colors.HexColor('#EAF1F7'); OFF=colors.HexColor('#F7F9FC'); CYAN=colors.HexColor('#0A8FC2'); ORANGE=colors.HexColor('#F2E6D7'); GREEN=colors.HexColor('#E7F0EC'); MUTED=colors.HexColor('#5F6B78'); RULE=colors.HexColor('#C7D1DB')
PW,PH=A4; LEFT=RIGHT=18*mm; TOP=20*mm; BOTTOM=16*mm

def extract_figure(nb_path, title, output_path):
    nb=json.loads(Path(nb_path).read_text())
    for c in nb['cells']:
        src=''.join(c.get('source',[]))
        if title not in src: continue
        for o in c.get('outputs',[]):
            d=o.get('data',{})
            if 'image/png' in d:
                b=d['image/png']; b=''.join(b) if isinstance(b,list) else b
                im=PILImage.open(BytesIO(base64.b64decode(b))).convert('RGB')
                im=im.crop((0,35,im.width,im.height))
                im.save(output_path)
                return
    raise RuntimeError('Figure not found: '+title)

extract_figure('04_segments_robustness.ipynb','Shuffled vs Ordered Validation','_biz_validation.png')
extract_figure('05_final_validation_reporting.ipynb','Period-Local Lift by Call Depth','_biz_lift.png')

styles=getSampleStyleSheet()
styles.add(ParagraphStyle(name='TitleNavy',parent=styles['Title'],fontName='Helvetica-Bold',fontSize=25,leading=29,textColor=NAVY,alignment=TA_LEFT,spaceAfter=9))
styles.add(ParagraphStyle(name='Subtitle',parent=styles['Normal'],fontName='Helvetica',fontSize=11.5,leading=16,textColor=MUTED,spaceAfter=10))
styles.add(ParagraphStyle(name='H1Navy',parent=styles['Heading1'],fontName='Helvetica-Bold',fontSize=17,leading=21,textColor=NAVY,spaceBefore=2,spaceAfter=8))
styles.add(ParagraphStyle(name='H2Navy',parent=styles['Heading2'],fontName='Helvetica-Bold',fontSize=12,leading=15,textColor=NAVY,spaceBefore=7,spaceAfter=5))
styles.add(ParagraphStyle(name='BodyBiz',parent=styles['BodyText'],fontName='Helvetica',fontSize=9.5,leading=14,textColor=TEXT,spaceAfter=7))
styles.add(ParagraphStyle(name='SmallBiz',parent=styles['BodyText'],fontName='Helvetica',fontSize=8.3,leading=12,textColor=TEXT,spaceAfter=4))
styles.add(ParagraphStyle(name='CaptionBiz',parent=styles['BodyText'],fontName='Helvetica',fontSize=8.5,leading=11,textColor=TEXT,spaceBefore=4,spaceAfter=9))
styles.add(ParagraphStyle(name='CalloutTitle',parent=styles['BodyText'],fontName='Helvetica-Bold',fontSize=10.3,leading=13,textColor=NAVY,spaceAfter=3))
styles.add(ParagraphStyle(name='BigNumber',parent=styles['BodyText'],fontName='Helvetica-Bold',fontSize=20,leading=23,textColor=NAVY,alignment=TA_CENTER))
styles.add(ParagraphStyle(name='CenterSmall',parent=styles['BodyText'],fontName='Helvetica',fontSize=8.5,leading=11,textColor=MUTED,alignment=TA_CENTER))
frame=Frame(LEFT,BOTTOM,PW-LEFT-RIGHT,PH-TOP-BOTTOM,id='normal')

def footer(canvas,doc):
    canvas.saveState(); canvas.setStrokeColor(RULE); canvas.setLineWidth(.5); canvas.line(LEFT,11*mm,PW-RIGHT,11*mm); canvas.setFont('Helvetica',7.5); canvas.setFillColor(MUTED); canvas.drawString(LEFT,6.5*mm,'Term Deposit Customer Ranking - Business Recommendations'); canvas.drawRightString(PW-RIGHT,6.5*mm,str(doc.page)); canvas.restoreState()

def box(title,body,bg=PALE,border=CYAN):
    t=Table([[Paragraph(title,styles['CalloutTitle'])],[Paragraph(body,styles['BodyBiz'])]],colWidths=[PW-LEFT-RIGHT-4*mm],hAlign='LEFT')
    t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),bg),('BOX',(0,0),(-1,-1),.8,border),('LEFTPADDING',(0,0),(-1,-1),9),('RIGHTPADDING',(0,0),(-1,-1),9),('TOPPADDING',(0,0),(-1,-1),7),('BOTTOMPADDING',(0,0),(-1,-1),7)])); return t

def cards(items):
    t=Table([[Paragraph(v,styles['BigNumber']) for v,l in items],[Paragraph(l,styles['CenterSmall']) for v,l in items]],colWidths=[(PW-LEFT-RIGHT)/len(items)]*len(items))
    t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),OFF),('BOX',(0,0),(-1,-1),.6,RULE),('INNERGRID',(0,0),(-1,-1),.35,RULE),('TOPPADDING',(0,0),(-1,0),8),('BOTTOMPADDING',(0,1),(-1,1),8)])); return t

def clean_table(data,widths):
    t=Table(data,colWidths=widths,repeatRows=1,hAlign='LEFT')
    t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),NAVY),('TEXTCOLOR',(0,0),(-1,0),colors.white),('FONTNAME',(0,0),(-1,0),'Helvetica-Bold'),('FONTNAME',(0,1),(-1,-1),'Helvetica'),('FONTSIZE',(0,0),(-1,-1),8.2),('LEADING',(0,0),(-1,-1),10),('ALIGN',(1,1),(-1,-1),'RIGHT'),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LINEBELOW',(0,-1),(-1,-1),.6,RULE),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,OFF]),('LEFTPADDING',(0,0),(-1,-1),5),('RIGHTPADDING',(0,0),(-1,-1),5),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5)])); return t

doc=BaseDocTemplate('Business_Recommendations.pdf',pagesize=A4,leftMargin=LEFT,rightMargin=RIGHT,topMargin=TOP,bottomMargin=BOTTOM,title='Business Recommendations - Term Deposit Customer Ranking'); doc.addPageTemplates([PageTemplate(id='main',frames=[frame],onPage=footer)]); s=[]

s += [Spacer(1,9*mm),Paragraph('Business Recommendations',styles['TitleNavy']),Paragraph('Term Deposit Customer Ranking',ParagraphStyle('CoverSub',parent=styles['BodyText'],fontName='Helvetica-Bold',fontSize=15,leading=18,textColor=CYAN,spaceAfter=7)),Paragraph('Decision-focused recommendation based on the final executed 40,000-record analysis.',styles['Subtitle']),Spacer(1,5*mm),box('Executive decision','<b>Approve controlled pilot planning using unweighted Logistic Regression with all 12 valid pre-call predictors.</b> Keep HistGradientBoosting as a challenger. Do not approve unrestricted production deployment yet.'),Spacer(1,7*mm),cards([('1.85x','LR lift at 5% call depth'),('228','Subscribers captured in 1,528 calls'),('~123','Expected under random calling')]),Spacer(1,8*mm),Paragraph('What this means',styles['H1Navy']),Paragraph('The model should not decide whether a customer is eligible or predict a definitive yes/no outcome. Its role is to rank already eligible customers so the call centre contacts the most promising customers first and stops when available capacity is reached.',styles['BodyBiz']),box('Important constraint','The historical scores are useful for prioritisation but are <b>not yet reliable literal subscription probabilities</b>. Prospective recalibration and a live equal-capacity pilot are required before probability-based revenue or expected-value claims.',ORANGE,colors.HexColor('#C68B3C')),Spacer(1,7*mm),Paragraph('Recommended status: PILOT, NOT PRODUCTION',ParagraphStyle('DecisionLine',parent=styles['BodyText'],fontName='Helvetica-Bold',fontSize=12.5,leading=15,textColor=NAVY,alignment=TA_CENTER)),PageBreak()]

s += [Paragraph('1. Why Logistic Regression is the pilot champion',styles['H1Navy']),Paragraph('HistGradientBoosting looks stronger if the data are shuffled. The decision changes when the models are tested in source order, which better exposes instability between later campaign-like periods.',styles['BodyBiz']),clean_table([['Validation evidence','Logistic Regression','HistGradientBoosting'],['Shuffled ROC-AUC','0.684767','0.717461'],['Ordered weighted ROC-AUC','0.566290','0.551600'],['Ordered weighted PR-AUC','0.112626','0.096333'],['5% period-local lift','1.853857x','1.284690x']],[65*mm,48*mm,48*mm]),Spacer(1,6*mm),box('Decision logic','<b>HGB wins conventional shuffled ranking; LR wins the stricter ordered test and operational lift.</b> LR is also simpler to explain, monitor and challenge during a controlled pilot.',GREEN,colors.HexColor('#6A9A83')),Spacer(1,7*mm),Paragraph('Why not choose the highest shuffled ROC-AUC?',styles['H2Navy']),Paragraph('Because the bank will use the model on customers encountered after the historical training data, not on a randomly shuffled version of the same history. The large shuffled-to-ordered performance drop should dominate the deployment decision.',styles['BodyBiz']),Paragraph('What tuning contributed',styles['H2Navy']),Paragraph('Tuning did not produce a dramatic holdout ranking improvement. The tuned LR pre-call PR-AUC is 0.240265 versus 0.241676 for default LR, while tuned HGB improves from 0.268264 to 0.272820. The value of tuning is reproducible model selection, not evidence that complexity alone solves the business problem.',styles['BodyBiz']),Paragraph('What duration taught us',styles['H2Navy']),Paragraph('Completed-call duration dramatically increases retrospective ROC-AUC, but it is unavailable before the bank decides whom to call. It is diagnostic evidence of timing leakage, not a deployable predictor.',styles['BodyBiz']),PageBreak()]

s += [Paragraph('2. Conventional validation overstates stability',styles['H1Navy']),Paragraph('The same tuned, unweighted, pre-call model structures are evaluated under shuffled five-fold validation and expanding-window ordered validation. Only eight later blocks with sufficient earlier training data and at least 100 positive and 100 negative outcomes are used for the ordered headline metrics.',styles['BodyBiz']),Paragraph('Fig. 1: Shuffled vs Ordered Validation',styles['CaptionBiz']),Image('_biz_validation.png',width=170*mm,height=92*mm),Spacer(1,4*mm),box('Business interpretation','Both models lose substantial discrimination when evaluated in later ordered blocks. The pilot must therefore be treated as a <b>robustness test under controlled conditions</b>, not as rollout of a proven stable production model.',ORANGE,colors.HexColor('#C68B3C')),Spacer(1,5*mm),Paragraph('The source does not contain verified years, campaign IDs or trustworthy timestamps. These ordered blocks are a source-order robustness proxy, not true future-calendar validation.',styles['SmallBiz']),PageBreak()]

s += [Paragraph('3. What ranking can buy at limited call capacity',styles['H1Navy']),Paragraph('Lift asks: if the bank calls only the highest-ranked fraction of each eligible period, how concentrated are subscribers compared with random calling at the same volume?',styles['BodyBiz']),Paragraph('Fig. 2: Period-Local Lift by Call Depth',styles['CaptionBiz']),Image('_biz_lift.png',width=170*mm,height=87*mm),Spacer(1,4*mm),clean_table([['Call depth','LR calls','LR subscribers','Random expectation','LR lift'],['5%','1,528','228','122.99','1.853857x'],['10%','3,055','395','245.89','1.606389x'],['20%','6,108','689','491.63','1.401474x']],[25*mm,30*mm,35*mm,42*mm,30*mm]),Spacer(1,5*mm),box('Do not turn these depths into fixed quotas','5%, 10% and 20% are historical sensitivity points. The bank should choose call depth from available capacity and economics, then monitor whether incremental value remains positive as more of the list is called.'),PageBreak()]

s += [Paragraph('4. Who should be called - and what not to infer',styles['H1Navy']),Paragraph('<b>Operational rule:</b> score every already eligible customer using the 12 pre-call variables, rank them from highest to lowest, and call from the top until capacity is reached.',styles['BodyBiz']),box('Exploratory higher-conversion population','The descriptive rule <b>cellular contact AND (retired OR age >= 71 OR balance >= Q3)</b> identifies 6,774 customers, 778 subscribers and 11.49% conversion versus 7.24% overall. This is useful context, but it is <b>not</b> a recommendation to replace model ranking with a demographic rule or deploy a separate segment model.'),Spacer(1,7*mm),Paragraph('Guardrails for interpretation',styles['H2Navy']),Paragraph('<b>Do not use duration.</b> It is a post-call variable and leaks information unavailable at ranking time.',styles['BodyBiz']),Paragraph('<b>Do not treat the score as an exact probability.</b> Period-weighted ECE is 0.044442 for LR and 0.035101 for HGB; no sigmoid or isotonic recalibration model was fitted.',styles['BodyBiz']),Paragraph('<b>Do not claim customer-level independence.</b> Pseudo-profile grouping is a sensitivity check because no true customer ID exists.',styles['BodyBiz']),Paragraph('<b>Do not infer causality from historical feature importance.</b> Predictive association does not prove that changing an attribute would cause subscription.',styles['BodyBiz']),Spacer(1,4*mm),box('Primary data risk','`contact=unknown` appears in 12,765 records (31.9%). Better contact-channel and CRM history are likely to add more value than repeatedly tuning the same historical predictors.',ORANGE,colors.HexColor('#C68B3C')),PageBreak()]

s += [Paragraph('5. Controlled pilot design',styles['H1Navy']),Paragraph('The live pilot should test whether ranking creates incremental business value at the same assigned calling effort. The central comparison is the LR-ranked treatment arm against the bank\'s existing targeting process, if one is clearly defined, or random selection from the same eligible pool if it is not.',styles['BodyBiz']),box('Treatment arm','<b>LR-ranked eligible customers.</b> Use the final unweighted 12-feature pre-call LR model. Fix call capacity before outcomes are observed.'),Spacer(1,4*mm),box('Comparator','<b>Equal-capacity BAU or random eligible customers.</b> The same number of assigned calls must be used so the comparison tests prioritisation rather than call volume.',OFF,RULE),Spacer(1,4*mm),box('HGB challenger','Keep HGB as a shadow-ranked challenger or a separately randomised equal-capacity arm if volume permits. It should not replace LR before prospective evidence.',OFF,RULE),Spacer(1,7*mm),Paragraph('Primary outcome',styles['H2Navy']),Paragraph('<b>Subscriptions per 1,000 assigned calls.</b>',styles['BodyBiz']),Paragraph('Secondary monitoring',styles['H2Navy']),Paragraph('Contactability, complaints and opt-outs, repeat contacts, customer mix, agent time, realised call depth and any available cost-per-acquisition measure.',styles['BodyBiz']),Paragraph('Stop / review triggers',styles['H2Navy']),Paragraph('Pause or review if customer-outcome guardrails deteriorate materially, operational data quality fails, model-ranked performance does not beat the equal-capacity comparator, or performance changes materially across successive pilot windows.',styles['BodyBiz']),PageBreak()]

s += [Paragraph('6. Economics, implementation and decision gate',styles['H1Navy']),Paragraph('The historical data do not contain the bank inputs needed for a defensible ROI calculation. Profitability should therefore be calculated only after real operational values are supplied.',styles['BodyBiz']),box('Required business inputs','<b>Net contribution per subscription</b>, <b>cost per assigned/attempted call</b>, any additional acquisition/servicing cost, and actual capacity for the pilot window.'),Spacer(1,6*mm),Paragraph('Simple pilot economics',styles['H2Navy']),Paragraph('<b>Incremental subscriptions</b> = subscriptions in LR-ranked arm - subscriptions in equal-capacity comparator.',styles['BodyBiz']),Paragraph('<b>Incremental value</b> = incremental subscriptions x net contribution per subscription - incremental operating costs.',styles['BodyBiz']),Spacer(1,5*mm),Paragraph('Implementation priorities',styles['H2Navy']),Paragraph('1. Freeze eligibility rules and call capacity before scoring.<br/>2. Generate the LR ranking before campaign calls begin.<br/>3. Preserve comparator assignment and customer IDs.<br/>4. Record reliable timestamps, campaign IDs, contact outcomes and repeat contacts.<br/>5. Evaluate uplift and calibration prospectively before broader deployment.',styles['BodyBiz']),Spacer(1,6*mm),box('Final decision','<b>APPROVE FOR CONTROLLED PILOT PLANNING.</b><br/><b>DO NOT APPROVE FOR UNRESTRICTED PRODUCTION DEPLOYMENT.</b><br/><br/>The historical evidence supports using LR to prioritise calls, but the ordered-performance drop means the business case must be confirmed prospectively.',GREEN,colors.HexColor('#6A9A83')),Spacer(1,7*mm),Paragraph('Evidence source: all analytical metrics, tables and figures in this report are produced by the final executed notebooks 01-05 in the repository.',styles['SmallBiz'])]

doc.build(s)
Path('_biz_validation.png').unlink(missing_ok=True); Path('_biz_lift.png').unlink(missing_ok=True)
print('Business_Recommendations.pdf created')
